/**
 * Demo hero — a realistic six-week history generated by playing the real game engine on a fixed
 * reference calendar, then shifting every date so the story ends today. Because it is simulated
 * (not hand-written), every number is internally consistent: levels, streaks, quests, achievements,
 * weekly challenges and the transaction ledger all agree.
 */
import type { CategoryId, DateKey, GameState, JournalEntry, PartyMember, Quest } from '@/types';
import { emptyState } from '@/data/defaults';
import { addDays, daysInMonth, diffDays, parseDateKey, startOfDay, toDateKey } from '@/lib/date';
import { createRng } from '@/lib/random';
import { blankQuest, questsForToday } from '@/lib/engine/quests';
import {
  claimEvent,
  claimWeekly,
  completeOnboarding,
  completeQuest,
  createGoal,
  logActivity,
  progressQuest,
  saveJournal,
  setGoalProgress,
  syncDay,
  updateProfile,
  updateSettings,
} from '@/lib/engine/gameEngine';
import { currentWeekKey } from '@/lib/engine/weekly';
import { uid } from '@/lib/id';

export const DEMO_PROFILE_ID = 'demo-hero';

/** The reference calendar the simulation runs on (a Wednesday). */
const REF_TODAY: DateKey = '2026-10-14';
const HISTORY_DAYS = 41;
/** Days (relative to the start) with no activity. The last one ends the previous streak. */
const GAP_DAYS = new Set([9, 27]);

/** Categories the hero works in (kept to a focused set, like a real player). */
/** Daily-quest categories the hero takes on (a focused routine, like a real player). */
const HERO_CATEGORIES = new Set<CategoryId>(['work', 'learning', 'reading', 'cleaning']);

const atRef = (key: DateKey, h: number, m = 0) => {
  const d = parseDateKey(key);
  d.setHours(h, m, 0, 0);
  return d.getTime();
};

export interface DemoPlan {
  seed: string;
  /** Total minutes of morning deep work, spread over a few days, so the XP total lands exactly. */
  calibrateMinutes: number;
  calibrationDays: number[];
  /** Chance of doing each fitting daily quest. */
  dailyChance: number;
  spanishChance: number;
  readingChance: number;
  spanishXP: number;
  readingXP: number;
}

export const DEFAULT_PLAN: DemoPlan = { seed: 'demo-g', calibrateMinutes: 245, calibrationDays: [1, 4, 8, 12, 15, 19, 23, 30], dailyChance: 0.4, spanishChance: 0.6, readingChance: 0.4, spanishXP: 180, readingXP: 80 };

function simulate(plan: DemoPlan): GameState {
  const start = addDays(REF_TODAY, -HISTORY_DAYS);
  const rng = createRng(plan.seed);
  let s = completeOnboarding(
    emptyState(),
    { name: 'Alex', focusAreas: ['productivity', 'learning', 'fitness', 'reading'], difficulty: 'hardcore', classId: 'strategist' },
    atRef(start, 8, 40),
  ).state;
  s = { ...s, profile: { ...s.profile!, id: DEMO_PROFILE_ID, playerTag: 'Player_4821' } };
  s = updateProfile(s, { dailyGoal: 500 }, atRef(start, 8, 41)).state;
  s = updateSettings(s, { social: { enabled: true } }, atRef(start, 8, 42)).state;

  // The hero's own repeating quests (they came with the hero, so they don't count as newly created).
  const own = (q: Partial<Quest> & Pick<Quest, 'title' | 'category'>) => blankQuest({ kind: 'custom', periodKey: start, ...q }, atRef(start, 8, 45));
  s = {
    ...s,
    quests: [
      ...s.quests,
      own({ title: 'Spanish practice', description: 'One lesson plus ten new words.', category: 'learning', difficulty: 'hard', xpReward: plan.spanishXP, target: { amount: 20, unit: 'minutes' }, timerMinutes: 20, repeatSchedule: { type: 'daily' }, order: 1 }),
      own({ title: 'Read before bed', description: 'Phone in another room, book open.', category: 'reading', difficulty: 'medium', xpReward: plan.readingXP, target: { amount: 15, unit: 'minutes' }, timerMinutes: 15, repeatSchedule: { type: 'daily' }, order: 2 }),
      own({ title: 'Reset the desk', description: 'Clear the desk for the week ahead.', category: 'cleaning', difficulty: 'easy', xpReward: 30, repeatSchedule: { type: 'weekly', days: [0] }, order: 3 }),
    ],
  };

  for (let day = 0; day <= HISTORY_DAYS; day++) {
    const key = addDays(start, day);
    const isLast = day === HISTORY_DAYS;
    s = syncDay(s, atRef(key, 7, 50)).state;
    if (GAP_DAYS.has(day)) continue;
    const weekday = parseDateKey(key).getDay();

    // 09:00 — an occasional deep-work block before the day starts.
    const slot = plan.calibrationDays.indexOf(day);
    if (slot >= 0 && plan.calibrateMinutes > 0) {
      const n = plan.calibrationDays.length;
      const each = Math.floor(plan.calibrateMinutes / n);
      const minutes = each + (slot === 0 ? plan.calibrateMinutes - each * n : 0);
      if (minutes > 0) s = logActivity(s, { category: 'work', duration: minutes, label: 'Deep work', autoProgress: false }, atRef(key, 9, 0)).state;
    }

    // 10:00 / 13:00 / 16:00 — today's board: quests that fit the hero's routine.
    const board = questsForToday(s.quests, key).filter((q) => q.kind === 'daily' || q.kind === 'starter');
    let hour = 10;
    for (const q of board) {
      if (q.completed || !HERO_CATEGORIES.has(q.category)) continue;
      if (rng() > plan.dailyChance && !(day === 0 && q.kind === 'starter')) continue;
      const t = atRef(key, hour, 0);
      if (q.target?.unit === 'minutes') s = logActivity(s, { category: q.category, duration: q.target.amount, questId: q.id }, t).state;
      else if (q.target && q.target.unit !== 'times') s = progressQuest(s, q.id, q.target.amount, t).state;
      else s = completeQuest(s, q.id, t).state;
      hour += 3;
      if (isLast || hour > 16) break;
    }
    if (isLast) break;

    // 18:30 — training three times a week, a walk on most other days.
    if ([1, 3, 5].includes(weekday)) {
      s = logActivity(s, { category: 'exercise', duration: 25 + Math.round(rng() * 2) * 5, label: 'Strength training', autoProgress: false }, atRef(key, 18, 30)).state;
    } else if (rng() > 0.35) {
      s = logActivity(s, { category: 'walking', duration: 20 + Math.round(rng() * 3) * 5, label: 'Evening walk', amount: 2 + Math.round(rng() * 15) / 10, unit: 'km', autoProgress: false }, atRef(key, 18, 30)).state;
    }

    // 20:00 — Spanish. 22:15 — reading. Sunday afternoon — desk reset.
    const spanish = s.quests.find((q) => q.title === 'Spanish practice');
    if (rng() < plan.spanishChance) s = logActivity(s, { category: 'learning', duration: 20, questId: spanish?.id ?? null, label: 'Spanish' }, atRef(key, 20, 0)).state;
    const read = s.quests.find((q) => q.title === 'Read before bed');
    if (rng() < plan.readingChance) s = logActivity(s, { category: 'reading', duration: 15, questId: read?.id ?? null, label: 'Reading' }, atRef(key, 22, 15)).state;
    const desk = s.quests.find((q) => q.title === 'Reset the desk');
    if (weekday === 0 && desk && !desk.completed) s = completeQuest(s, desk.id, atRef(key, 16, 0)).state;

    // Claim anything that's ready in the evening.
    for (const wk of s.weeklies) for (const c of wk.challenges) if (c.readyAt && !c.claimed) s = claimWeekly(s, c.id, atRef(key, 21, 0)).state;
    for (const rec of Object.values(s.meta.events)) if (rec.completedAt && !rec.claimedAt) s = claimEvent(s, rec.key, atRef(key, 21, 5)).state;

    // A journal entry now and then.
    if (day % 5 === 2) {
      s = saveJournal(s, { dateKey: key, text: JOURNAL_LINES[Math.floor(day / 5) % JOURNAL_LINES.length], mood: (3 + Math.round(rng() * 2)) as JournalEntry['mood'], photoIds: [] }, atRef(key, 22, 40)).state;
    }

    if (day === 6) {
      s = createGoal(s, { title: 'Learn Spanish', description: 'Hold a real conversation on my trip in spring.', target: 'Reach conversational level', category: 'learning', deadline: '2026-12-31' }, atRef(key, 21, 30)).state;
      s = createGoal(s, { title: 'Run a 10K', description: 'Build up slowly — no injuries.', target: 'Finish a 10K race', category: 'running', deadline: '2027-03-15', milestones: [{ title: 'Run 3 km without stopping', xpReward: 75 }, { title: 'Run 5 km', xpReward: 100 }, { title: 'Run 8 km', xpReward: 125 }, { title: 'Race day: 10 km', xpReward: 200 }] }, atRef(key, 21, 35)).state;
    }
    if (day === 20) s = { ...s, party: demoParty(atRef(key, 21, 0), s.settings.weekStartsOn) };
    if (day === 34) {
      const spanishGoal = s.goals.find((g) => g.title === 'Learn Spanish');
      if (spanishGoal) s = setGoalProgress(s, spanishGoal.id, 42, atRef(key, 21, 40)).state;
    }
  }
  return s;
}

const JOURNAL_LINES = [
  'Strong start to the week. The morning deep work block is starting to feel automatic.',
  'Tired today, but I still got the walk in. Small wins count.',
  'Finally finished the API refactor. Spanish lesson was fun — learned 12 new words.',
  'Had a really productive day. Keeping my phone in another room while working changes everything.',
  'Missed a day last week and it felt bad for a second — then I just started again. Back on track.',
  'Ran into friends after training and stayed out longer than planned. Worth it.',
  'Planning the 10K: going slow, three runs a week starting next month.',
  'Reading streak is quietly becoming my favorite part of the day.',
];

/* ───────────────────────── Shifting the reference calendar to today ───────────────────────── */

function shiftKey(key: DateKey | null, days: number): DateKey | null {
  return key ? addDays(key, days) : key;
}

function shiftTs(ts: number | null, days: number): number | null {
  if (ts === null) return null;
  const key = toDateKey(ts);
  return startOfDay(addDays(key, days)) + (ts - startOfDay(key));
}

function shiftState(s: GameState, days: number): GameState {
  if (!days) return s;
  const k = (key: DateKey | null) => shiftKey(key, days);
  const t = (ts: number | null) => shiftTs(ts, days);
  const tt = (ts: number) => shiftTs(ts, days)!;
  return {
    ...s,
    profile: s.profile && { ...s.profile, createdAt: tt(s.profile.createdAt) },
    meta: {
      ...s.meta,
      onboardedAt: t(s.meta.onboardedAt),
      lastSeenDate: k(s.meta.lastSeenDate),
      restDays: s.meta.restDays.map((d) => k(d)!),
      momentum: { ...s.meta.momentum, lastAt: s.meta.momentum.lastAt ? tt(s.meta.momentum.lastAt) : 0 },
      rerolls: { ...s.meta.rerolls, dateKey: s.meta.rerolls.dateKey ? k(s.meta.rerolls.dateKey)! : '' },
      streakReset: s.meta.streakReset && { ...s.meta.streakReset, brokenOn: k(s.meta.streakReset.brokenOn)!, protectableDay: k(s.meta.streakReset.protectableDay) },
      events: Object.fromEntries(Object.entries(s.meta.events).map(([key, rec]) => [key, { ...rec, completedAt: t(rec.completedAt), claimedAt: t(rec.claimedAt) }])),
    },
    quests: s.quests.map((q) => ({ ...q, createdAt: tt(q.createdAt), completedAt: t(q.completedAt), periodKey: k(q.periodKey), dueDate: k(q.dueDate), lastCompletedKey: k(q.lastCompletedKey), order: q.order })),
    activities: s.activities.map((a) => ({ ...a, timestamp: tt(a.timestamp), dateKey: k(a.dateKey)! })),
    transactions: s.transactions.map((x) => ({ ...x, timestamp: tt(x.timestamp), dateKey: k(x.dateKey)! })),
    achievements: s.achievements.map((a) => ({ ...a, unlockedAt: tt(a.unlockedAt) })),
    goals: s.goals.map((g) => ({
      ...g,
      createdAt: tt(g.createdAt),
      completedAt: t(g.completedAt),
      deadline: g.deadline,
      milestones: g.milestones.map((m) => ({ ...m, completedAt: t(m.completedAt) })),
    })),
    journal: s.journal.map((j) => ({ ...j, dateKey: k(j.dateKey)!, createdAt: tt(j.createdAt), updatedAt: tt(j.updatedAt) })),
    weeklies: s.weeklies.map((w) => ({
      ...w,
      id: k(w.weekKey)!,
      weekKey: k(w.weekKey)!,
      createdAt: tt(w.createdAt),
      challenges: w.challenges.map((c) => ({ ...c, readyAt: t(c.readyAt), claimedAt: t(c.claimedAt) })),
    })),
    challenges: s.challenges,
    party: s.party,
    session: null,
  };
}

/**
 * Today's actions happened earlier today — never in the future relative to `now`, and never inside
 * the 5–8 AM window (that would quietly earn the Early Riser achievement).
 */
function settleToday(s: GameState, now: number): GameState {
  const today = toDateKey(now);
  const dayStart = startOfDay(today);
  const future = new Set<number>();
  const note = (ts: number | null) => {
    if (ts !== null && ts > now && toDateKey(ts) === today) future.add(ts);
  };
  s.activities.forEach((a) => note(a.timestamp));
  s.transactions.forEach((x) => note(x.timestamp));
  s.quests.forEach((q) => note(q.completedAt));
  s.achievements.forEach((a) => note(a.unlockedAt));
  if (!future.size) return s;

  const slots: number[] = [];
  let t = now - 25 * 60_000;
  while (slots.length < future.size) {
    const hour = new Date(t).getHours();
    if (hour >= 5 && hour < 8) t = dayStart + 4 * 3_600_000 + 59 * 60_000;
    slots.push(Math.max(dayStart + 1000, Math.min(t, now - 1000)));
    t -= 41 * 60_000;
  }
  slots.sort((a, b) => a - b);
  const map = new Map([...future].sort((a, b) => a - b).map((ts, i) => [ts, slots[i]]));
  const m = (ts: number) => map.get(ts) ?? ts;
  const mn = (ts: number | null) => (ts === null ? null : m(ts));
  return {
    ...s,
    activities: s.activities.map((a) => ({ ...a, timestamp: m(a.timestamp) })),
    transactions: s.transactions.map((x) => ({ ...x, timestamp: m(x.timestamp) })),
    quests: s.quests.map((q) => ({ ...q, completedAt: mn(q.completedAt) })),
    achievements: s.achievements.map((a) => ({ ...a, unlockedAt: m(a.unlockedAt) })),
    meta: { ...s.meta, momentum: { ...s.meta.momentum, lastAt: Math.min(s.meta.momentum.lastAt, now) } },
  };
}

function demoParty(now: number, weekStartsOn: 0 | 1): PartyMember[] {
  const ago = (h: number) => now - h * 3_600_000;
  // Each card reflects the week and month it was shared in; weekly and monthly totals are scaled to
  // how far into that period the friend was, so a Monday never shows a full week of XP.
  const member = (m: Omit<PartyMember, 'addedAt' | 'updatedAt' | 'weekKey' | 'monthKey'>): PartyMember => {
    const day = toDateKey(m.cardAt);
    const weekKey = currentWeekKey(day, weekStartsOn);
    const weekShare = (diffDays(weekKey, day) + 0.6) / 7;
    const monthShare = (Number(day.slice(8, 10)) - 0.4) / daysInMonth(day);
    const scale = (v: number | null, share: number) => (v === null ? null : Math.round((v * share) / 10) * 10);
    return { ...m, weeklyXP: scale(m.weeklyXP, weekShare), monthlyXP: scale(m.monthlyXP, monthShare), weekKey, monthKey: day.slice(0, 7), addedAt: ago(24 * 20), updatedAt: m.cardAt };
  };
  return [
    member({ id: 'demo-sam', name: 'Sam', classId: 'athlete', avatar: { sigil: 'sigil:bolt', background: 'bg:ember', frame: 'frame:hex', aura: 'aura:glow' }, titleId: 'title:athlete', level: 16, totalXP: 10_150, weeklyXP: 1_280, monthlyXP: 2_940, questsCompleted: 61, achievements: 15, streak: 9, cardAt: ago(5) }),
    member({ id: 'demo-maya', name: 'Maya', classId: 'scholar', avatar: { sigil: 'sigil:tome', background: 'bg:nebula', frame: 'frame:cyber', aura: 'aura:pulse' }, titleId: 'title:scholar', level: 21, totalXP: 17_820, weeklyXP: 1_960, monthlyXP: 4_480, questsCompleted: 118, achievements: 24, streak: 31, cardAt: ago(11) }),
    member({ id: 'demo-jordan', name: 'Jordan', classId: 'creator', avatar: { sigil: 'sigil:quill', background: 'bg:aurora', frame: 'frame:simple', aura: 'aura:none' }, titleId: 'title:getting_started', level: 12, totalXP: 6_310, weeklyXP: 860, monthlyXP: 1_720, questsCompleted: 38, achievements: 11, streak: 4, cardAt: ago(28) }),
    member({ id: 'demo-anon', name: 'Player_2048', classId: 'explorer', avatar: { sigil: 'sigil:compass', background: 'bg:midnight', frame: 'frame:simple', aura: 'aura:none' }, titleId: null, level: 19, totalXP: 14_020, weeklyXP: null, monthlyXP: null, questsCompleted: null, achievements: 19, streak: null, cardAt: ago(50) }),
  ];
}

/**
 * Build the demo state for `now`. The simulation is deterministic, so the hero always lands on the
 * same stats: Level 18, 12,480 XP, a 14-day streak, 73 quests completed and 18 achievements.
 */
export function buildDemoState(now: number, plan: DemoPlan = DEFAULT_PLAN): GameState {
  const simulated = simulate(plan);
  const today = toDateKey(now);
  let s = settleToday(shiftState(simulated, diffDays(REF_TODAY, today)), now);
  const weekKey = currentWeekKey(today, s.settings.weekStartsOn);
  s = {
    ...s,
    // Friends' cards are "fresh" relative to the real date.
    party: demoParty(now, s.settings.weekStartsOn),
    challenges: [
      { id: uid('c_'), opponentId: 'demo-sam', opponentName: 'Sam', metric: 'weekly_xp', weekKey, reward: 250, createdAt: Math.max(startOfDay(weekKey), now - 2 * 86_400_000), status: 'active', resolvedAt: null, myScore: null, theirScore: null },
    ],
    meta: { ...s.meta, lastSummaryDate: today },
  };
  // Show off a little: the hero wears what they've earned.
  const owned = new Set(s.meta.inventory);
  const pick = (id: string, fallback: string) => (owned.has(id) ? id : fallback);
  const p = s.profile!;
  s.profile = {
    ...p,
    titleId: owned.has('title:consistent') ? 'title:consistent' : p.titleId,
    badgeId: owned.has('badge:flame') ? 'badge:flame' : p.badgeId,
    avatar: { ...p.avatar, frame: pick('frame:runic', p.avatar.frame), background: pick('bg:abyss', p.avatar.background), aura: pick('aura:glow', p.avatar.aura) },
  };
  // Bring the world up to date for the real "now" (current week, today's board, unlocks).
  return syncDay(s, now).state;
}

/** Exposed for tests and tuning. */
export const __demo = { simulate, REF_TODAY, HISTORY_DAYS };
