import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  Accessibility,
  AlarmClockOff,
  ArrowLeft,
  ArrowRight,
  Atom,
  Award,
  BadgeCheck,
  BatteryCharging,
  Bell,
  BicepsFlexed,
  BookOpen,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  BrushCleaning,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  Castle,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  CircleHelp,
  Clock,
  Cloud,
  CloudFog,
  CloudRain,
  CloudSun,
  CodeXml,
  Cog,
  Coins,
  Compass,
  Contrast,
  Copy,
  Crosshair,
  Crown,
  Database,
  Diamond,
  Dices,
  Download,
  Dumbbell,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  Footprints,
  Gem,
  Ghost,
  Gift,
  Goal,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HeartPulse,
  History,
  Hourglass,
  House,
  ImagePlus,
  Infinity as InfinityIcon,
  Info,
  Library,
  Lightbulb,
  Link,
  Lock,
  LockOpen,
  LogOut,
  Medal,
  Milestone,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  NotebookPen,
  NotebookText,
  Palette,
  Pause,
  PenLine,
  PencilRuler,
  PenTool,
  Pencil,
  Play,
  Plus,
  Quote,
  RefreshCw,
  Rocket,
  RotateCcw,
  ScrollText,
  Settings,
  Shapes,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkle,
  Sparkles,
  SportShoe,
  Sprout,
  Square,
  Star,
  Sun,
  Sunrise,
  Sword,
  Swords,
  Target,
  Telescope,
  Timer,
  Tornado,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Undo2,
  Upload,
  UserPlus,
  UserRound,
  Users,
  Volleyball,
  Volume2,
  VolumeX,
  WandSparkles,
  WifiOff,
  X,
  Zap,
} from 'lucide-react';

const REGISTRY = {
  accessibility: Accessibility,
  'alarm-clock-off': AlarmClockOff,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  atom: Atom,
  award: Award,
  'badge-check': BadgeCheck,
  'battery-charging': BatteryCharging,
  bell: Bell,
  'biceps-flexed': BicepsFlexed,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  brain: Brain,
  'briefcase-business': BriefcaseBusiness,
  'brush-cleaning': BrushCleaning,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  'calendar-heart': CalendarHeart,
  castle: Castle,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'circle-help': CircleHelp,
  clock: Clock,
  cloud: Cloud,
  'cloud-fog': CloudFog,
  'cloud-rain': CloudRain,
  'cloud-sun': CloudSun,
  'code-xml': CodeXml,
  cog: Cog,
  coins: Coins,
  compass: Compass,
  contrast: Contrast,
  copy: Copy,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  diamond: Diamond,
  dices: Dices,
  download: Download,
  dumbbell: Dumbbell,
  'ellipsis-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  flame: Flame,
  'flame-kindling': FlameKindling,
  flower: Flower,
  'flower-2': Flower2,
  footprints: Footprints,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  goal: Goal,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  history: History,
  hourglass: Hourglass,
  house: House,
  'image-plus': ImagePlus,
  infinity: InfinityIcon,
  info: Info,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  'lock-open': LockOpen,
  'log-out': LogOut,
  medal: Medal,
  milestone: Milestone,
  monitor: Monitor,
  moon: Moon,
  'moon-star': MoonStar,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  'notebook-pen': NotebookPen,
  'notebook-text': NotebookText,
  palette: Palette,
  pause: Pause,
  'pen-line': PenLine,
  'pencil-ruler': PencilRuler,
  'pen-tool': PenTool,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  quote: Quote,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  'scroll-text': ScrollText,
  settings: Settings,
  shapes: Shapes,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sparkle: Sparkle,
  sparkles: Sparkles,
  'sport-shoe': SportShoe,
  sprout: Sprout,
  square: Square,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  sword: Sword,
  swords: Swords,
  target: Target,
  telescope: Telescope,
  timer: Timer,
  tornado: Tornado,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  'undo-2': Undo2,
  upload: Upload,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  volleyball: Volleyball,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'wand-sparkles': WandSparkles,
  'wifi-off': WifiOff,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

export interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName | string;
  /** Accessible label. Without it the icon is decorative (aria-hidden). */
  label?: string;
}

export function Icon({ name, label, size = 18, strokeWidth = 1.85, ...rest }: IconProps) {
  const Component = (REGISTRY as Record<string, LucideIcon>)[name] ?? Sparkle;
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden={label ? undefined : true} aria-label={label} role={label ? 'img' : undefined} focusable="false" {...rest} />;
}
